import xml.etree.ElementTree as ET

# Namespaces
XSI_NS = "http://www.w3.org/2001/XMLSchema-instance"
ALTO_NS = "http://www.loc.gov/standards/alto/ns-v4#"

# Schema location
SCHEMA_LOCATION = (
    "http://www.loc.gov/standards/alto/ns-v4# "
    "http://www.loc.gov/standards/alto/v4/alto-4-2.xsd"
)

def write_xml(tree: ET.ElementTree, out_path):
    """
    Write XML tree to file with XML declaration and a controlled attribute order:
    1. xmlns:xsi
    2. xmlns (default namespace)
    3. xsi:schemaLocation
    """
    root = tree.getroot()
    # Remove existing attributes that may conflict
    root.attrib.pop(f"{{{XSI_NS}}}schemaLocation", None)
    
    # Convert tree to string
    xml_str = ET.tostring(root, encoding="utf-8").decode("utf-8")
    
    # Build the XML declaration manually with the desired attribute order
    xml_decl = '<?xml version="1.0" encoding="UTF-8"?>\n'
    
    # Construct the root start tag manually
    start_tag = (
        f'<alto xmlns:xsi="{XSI_NS}" '
        f'xmlns="{ALTO_NS}" '
        f'xsi:schemaLocation="{SCHEMA_LOCATION}">'
    )
    
    # Remove the autogenerated root start tag from xml_str
    inner_xml = xml_str.split(">", 1)[1].rsplit("</alto>", 1)[0]
    
    # Combine everything
    final_xml = f"{xml_decl}{start_tag}{inner_xml}</alto>"
    
    # Write to file
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(final_xml)
    
    print(f"Updated: {out_path.name}")
